const types = {
  AUTH_SIGNIN: 'AUTH_SIGNIN',
  AUTH_SIGNOUT: 'AUTH_SIGNOUT',

  FIREBASE_CONNECTED: 'FIREBASE_CONNECTED',
  FIREBASE_ERROR: 'FIREBASE_ERROR',

  JOBS_LOADED: 'JOBS_LOADED',
  JOBS_DETAILS_LOADED: 'JOBS_DETAILS_LOADED',

  MODAL_TOGGLE: 'MODAL_TOGGLE',
}
export default types;